version: '4.0.1'
services:
  nest-api:
    container_name: sar-manage-graphql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7001:7001
    depends_on:
      - postgres
    env_file:
      - .env
